name: Unit Test Run

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: python -m coverage run --branch --source=scripts -m pytest ./tests/
    # - name: Coverage report
    #   run: coverage report --skip-empty
    # - name: Upload coverage reports to Codecov
    #   uses: codecov/codecov-action@v3
