name: build

on:
  push:
  pull_request:

jobs:
  frontendTesting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/client
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: |
          npm install --save-dev jest@latest @testing-library/react@latest
          npm ci

      - name: Run tests
        run: npx jest /test_client

  backendTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Adjust the Python version as needed

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev flac ffmpeg
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test with pytest
        run: python -m coverage run --branch --source=scripts -m pytest ./tests/
